---
kind: pipeline
type: docker
name: default

steps:
- name: Testing Drone
  image: apisec/drone-scan:latest
  environment:
     scanner: Super_3
     email: false
     hostUrl: https://developer.apisec.ai
     projectName: Test
     profile: Master
     report: RUN_SUMMARY
     vulnerabilityFlag: false
     PASSWORD:
        from_secret: PASSWORD
     USERNAME:
        from_secret: USERNAME
