---
kind: pipeline
type: docker
name: default

steps:
- name: Testing Drone
  image: apisec/drone-scan:latest
  environment:
     scanner: Super_3
     email: false
     hostUrl: https://developer.apisec.ai
     projectName: Test
     profile: Master
     report: RUN_SUMMARY
     vulnerabilityFlag: false
     secrets_apisec_password:
        from_secret: secrets_apisec_password
     secrets_apisec_username:
        from_secret: secrets_apisec_username
