pipeline:
  build:
    image: golang:latest
    pull: true
    commands:
      - go get
      - go build
      - go test

  frontend:
    image: node:6
    commands:
      - npm install
      - npm test

  notify:
    image: plugins/docker
    channel: developers
    username: drone
    
    


 
  
   
