kind: pipeline
name: Build
trigger:
  event:
  - push
steps: 
- name: Drone
  image: ubuntu:latest
  environment:
    PASSWORD:
      from_secret: apisec-password
    USERNAME:
      from_secret: apisec-username
  commands:
  - ls
  - apt-get update 
  - apt-get install -y wget jq curl
  - wget https://raw.githubusercontent.com/apisec-inc/apisec-scripts/master/apisec_job_invoke_script.sh?token=AVOLEQ4FVVPJJ3DPAME4JELBS56SI -O apisec_job_invoke_script.sh;bash apisec_job_invoke_script.sh --host https://developer.apisec.ai --username {Username} --password {Password} --project "HMAC" --profile Master --scanner Super_1 --emailReport true --reportType RUN_SUMMARY
  
   
